apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  proxy.conf: |
    server {
        listen 80;

        location /sns {
            proxy_pass http://kourier-internal.kourier-system.svc.cluster.local/;

            proxy_set_header Host main.default.svc.cluster.local;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
